### ISSUE TITLE
Build fails in Github workflow (v 2.0.5)

### ISSUE THREAD

**Issue by fs86** [LuaJIT/LuaJIT#999]
I am trying to build a custom Docker image with integrated LuaJIT 2.0.5 but the build fails in my github workflow. It says that no target architecture is defined. Does anyone have an idea why this is happening?

**Github workflow**
```yml
name: build python-luajit-nodejs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - python-luajit-nodejs/**

jobs:
  push:
    name: "pterodactyl-images:python-${{ matrix.tag }}-luajit-nodejs"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - '3.11'
    steps:
      - uses: actions/checkout@v3
      # Setup QEMU for ARM64 Build
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./python-luajit-nodejs
          file: ./python-luajit-nodejs/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/XXXXX/pterodactyl-images:python-${{ matrix.tag }}-luajit-nodejs
```

**Dockerfile**
```
FROM       debian:bullseye

LABEL       author="XXXXX" maintainer="XXXXX"

RUN         apt update \
                && apt -y install git gcc g++ make ca-certificates dnsutils curl iproute2 ffmpeg procps libc6-dev \
                && curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && apt install -y nodejs \
                && curl https://luajit.org/download/LuaJIT-2.0.5.tar.gz | tar xvz \
                && cd LuaJIT-2.0.5 && make && make install \
                && corepack enable \
                && useradd -m -d /home/container container

USER       container
ENV        USER=container HOME=/home/container
WORKDIR    /home/container

COPY       ./../entrypoint.sh /entrypoint.sh
CMD        [ "/bin/bash", "/entrypoint.sh" ]
```

**Build output**
```
#10 441.0 ==== Building LuaJIT 2.0.5 ====
#10 441.0 make -C src
#10 441.1 make[1]: Entering directory '/LuaJIT-2.0.5/src'
#10 441.4 lj_arch.h:55:2: error: #error "No support for this architecture (yet)"
#10 441.4    55 | #error "No support for this architecture (yet)"
#10 441.4       |  ^~~~~
#10 441.4 lj_arch.h:294:2: error: #error "No target architecture defined"
#10 441.4   294 | #error "No target architecture defined"
#10 441.4       |  ^~~~~
#10 441.7 lj_arch.h:55:2: error: #error "No support for this architecture (yet)"
#10 441.7    55 | #error "No support for this architecture (yet)"
#10 441.7       |  ^~~~~
#10 441.7 lj_arch.h:294:2: error: #error "No target architecture defined"
#10 441.7   294 | #error "No target architecture defined"
#10 441.7       |  ^~~~~
#10 442.0 lj_arch.h:55:2: error: #error "No support for this architecture (yet)"
#10 442.0    55 | #error "No support for this architecture (yet)"
#10 442.0       |  ^~~~~
#10 442.0 lj_arch.h:294:2: error: #error "No target architecture defined"
#10 442.0   294 | #error "No target architecture defined"
#10 442.0       |  ^~~~~
#10 442.4 lj_arch.h:55:2: error: #error "No support for this architecture (yet)"
#10 442.4    55 | #error "No support for this architecture (yet)"
#10 442.4       |  ^~~~~
#10 442.4 lj_arch.h:294:2: error: #error "No target architecture defined"
#10 442.4   294 | #error "No target architecture defined"
#10 442.4       |  ^~~~~
#10 442.7 lj_arch.h:55:2: error: #error "No support for this architecture (yet)"
#10 442.7    55 | #error "No support for this architecture (yet)"
#10 442.7       |  ^~~~~
#10 442.7 lj_arch.h:294:2: error: #error "No target architecture defined"
#10 442.7   294 | #error "No target architecture defined"
#10 442.7       |  ^~~~~
#10 443.0 lj_arch.h:55:2: error: #error "No support for this architecture (yet)"
#10 443.0    55 | #error "No support for this architecture (yet)"
#10 443.0       |  ^~~~~
#10 443.0 lj_arch.h:294:2: error: #error "No target architecture defined"
#10 443.0   294 | #error "No target architecture defined"
#10 443.0       |  ^~~~~
#10 443.0 Makefile:254: *** Unsupported target architecture.  Stop.
#10 443.0 make[1]: Leaving directory '/LuaJIT-2.0.5/src'
#10 443.0 make: *** [Makefile:110: default] Error 2
#10 ERROR: process "/bin/sh -c apt update             && apt -y install git gcc g++ make ca-certificates dnsutils curl iproute2 ffmpeg procps libc6-dev             && curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && apt install -y nodejs             && curl https://luajit.org/download/LuaJIT-2.0.5.tar.gz | tar xvz             && cd LuaJIT-2.0.5 && make && make install             && corepack enable             && useradd -m -d /home/container container" did not complete successfully: exit code: 2
------
 > [linux/arm64 2/4] RUN         apt update             && apt -y install git gcc g++ make ca-certificates dnsutils curl iproute2 ffmpeg procps libc6-dev             && curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && apt install -y nodejs             && curl https://luajit.org/download/LuaJIT-2.0.5.tar.gz | tar xvz             && cd LuaJIT-2.0.5 && make && make install             && corepack enable             && useradd -m -d /home/container container:
#10 442.7       |  ^~~~~
#10 443.0 lj_arch.h:55:2: error: #error "No support for this architecture (yet)"
#10 443.0    55 | #error "No support for this architecture (yet)"
#10 443.0       |  ^~~~~
#10 443.0 lj_arch.h:294:2: error: #error "No target architecture defined"
#10 443.0   294 | #error "No target architecture defined"
#10 443.0       |  ^~~~~
#10 443.0 Makefile:254: *** Unsupported target architecture.  Stop.
#10 443.0 make[1]: Leaving directory '/LuaJIT-2.0.5/src'
#10 443.0 make: *** [Makefile:110: default] Error 2
```
